
version: "3"
server:
  command: "php ./psr-worker.php"
  env:
    APP_HEADER_TRACE_ID_NAME: "X-SERVER-TRACE-ID"
    APP_HEADER_CDN_VERIFICATION_API_KEY_NAME: "X-CDN-VERIFICATION-API-KEY"
    APP_HEADER_CDN_VERIFICATION_API_SECRET_NAME: "X-CDN-VERIFICATION-API-SECRET"
    APP_ENV_SITE_TITLE: "X9GG/lb-web"
    APP_ENV_SITE_COPYRIGHT_YEAR: "2025"
    APP_ENV_SITE_COPYRIGHT_NAME: "X9GG LLC"
    APP_ENV_SITE_COPYRIGHT_URL: "https://x9gg.com"


http:
  address: 0.0.0.0:8080
  middleware: ["static"]
  static:
    dir: "./src/public"
    calculate_etag: false
    allow: [ ".webmanifest", ".png" , '.ico', '.svg']

logs:
  encoding: console
  output: stderr
  err_output: stderr



