version: "3"

include:
  - .rr.base.yaml

server:
  command: "php /worker/psr-worker.php"

http:
  pool:
    debug: false
    num_workers: 1
    max_jobs: 64
    allocation_timeout: 180s
    destroy_timeout: 120s

workers:
  pool:
    num_workers:  8
    max_jobs: 128
    allocation_timeout: 180s
    destroy_timeout: 180s
    
logs:
  mode: production
  level: error
