name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: sockets, zip
          tools: composer:v2

      - name: Install Dependencies
        run: |
          composer install --optimize-autoloader --no-dev --no-scripts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: x9gg/lb-web:latest
